#!/bin/bash

echo "Create new database with:"
echo ""
echo ""
echo "rm postcode-battle.db && sqlite3 postcode-battle.db"
echo ""
echo ""
echo "... and then execute the following commands in sqlite3:"
echo ""
echo ""
echo "CREATE TABLE lga ("
echo "  name character,"
echo "  id integer,"
echo "  area integer,"
echo "  population integer"
echo ");"
echo ""
echo ""
echo "CREATE TABLE attributeMetadata ("
echo "  AttributeID character,"
echo "  AttributeName character,"
echo "  AttributeDescription character,"
echo "  CategoryID character,"
echo "  CategoryName character,"
echo "  PositivePhrase character,"
echo "  NegativePhrase character,"
echo "  Comparator character,"
echo "  Denominator character,"
echo "  DenominatorRationale character,"
echo "  DataSourceLink character,"
echo "  DataSourceRationale character,"
echo "  DataSourceDate character"
echo ");"
echo ""
echo ""
echo "CREATE TABLE attributeValues ("
echo "  attributeId integer,"
echo "  lgaId integer,"
echo "  lga character,"
echo "  attributeValue number"
echo ");"
echo ""
echo ""
echo ".mode csv lga"
echo ".import 'data/LGAs - Sheet1.csv' lga"
echo ""
echo ".mode csv attributeMetadata"
echo ".import 'data/attributemetadata - Sheet1.csv' attributeMetadata"
echo ""
echo ".mode csv attributeValues"
echo ".import 'data/AttributeValues1[nrSchools] - Sheet1.csv' attributeValues"
echo ""
echo ""
echo "... then copy the database to the relevant path:"
echo ""
echo ""
echo "cp postcode-battle.db ../"
echo ""
echo ""
