#!/bin/bash

echo "Create new database with:"
echo ""
echo ""
echo "rm postcode-battle.db && sqlite3 postcode-battle.db"
echo ""
echo ""
echo "... and then execute the following commands in sqlite3:"
echo ""
echo ""
echo "CREATE TABLE lga ("
echo "  id integer,"
echo "  name character,"
echo "  area integer,"
echo "  population integer"
echo ");"
echo ""
echo ".mode csv lga"
echo ".import 'data/LGAs - Sheet1.csv' lga"
echo ""
echo ""
echo "... then copy the database to the relevant path:"
echo ""
echo ""
echo "cp postcode-battle.db ../"
echo ""
echo ""
